apiVersion: v1
kind: Service
metadata:
  name: db #name of the service
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod-label #from postgres pod
    app: demo-voting-app #from postgres pod