apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod #name of the pod
  labels:
    name: postgres-pod-label #can be same as the name of the pod
    app: demo-voting-app #name of the app
spec:
  containers:
    - name: postgres #name of the container
      image: postgres #image source
      ports:
        - containerPort: 5432 #listenning/exposed port
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"